package interactive.taskmanager.ui.theme.color

import androidx.compose.ui.graphics.Color

// global colors
val globalWhite = Color(0xFFFFFFFF)
val globalPurple = Color(0xffc569f7)
val globalBlue = Color(0xff15bbf4)
val globalGreen = Color(0xff1bd59a)
val globalBlack = Color(0xFF000000)
val yellowLight = Color(0xfffef8ed)
val globalGray = Color(0xFF959595)
val globalRed = Color(0xFFFF1A53)
val globalDisabled = Color(0x50000000)
val colorPrimary = Color(0xffffffff)
val colorTextPrimary = Color(0xde000000)
val colorTextSecondary = Color(0xFF737780)
val colorTextTertiary = Color(0xFFC0C0C0)
val colorTextPrimaryInverse = Color(0xdeffffff)
val colorTextSecondaryInverse = Color(0x8affffff)
val colorStatusBar = Color(0xFFFF1A53)
val colorBackground = Color(0xfff5f6f7)
val alertDialogActionColor = Color(0xFF007AFF)
val hyperlinkColor = Color(0xFF48B5CC)
val colorBackgroundPrimary = Color(0xFFFFFFFF)
val colorBackgroundSecondary = Color(0xFFF7F7F7)
val colorPrimaryDark = Color(0xffcccccc)
val globalLightPurple = Color(0xFFCC65F7)
val LightPurple = Color(0xFFDEE2FF)
val LightGreen = Color(0xFFD5FFD5)
val LightBlue = Color(0xFFD5F7FF)
val green = Color(0xFF4CAF50)
val yellow = Color(0xFFFFC107)
val red = Color(0xFFF44336)
val lineMidLight = Color(0xFFD7DDE2)